export const SAVE_NOTE = 'SAVE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const SELECT_NOTE = 'SELECT_NOTE';
export const UNSELECT_NOTE = 'UNSELECT_NOTE';
export const GET_COLOR_NOTE = 'GET_COLOR_NOTE';
export const CHANGE_COLOR_NOTE = 'CHANGE_COLOR_NOTE';
export const GET_NOTE_INDEX = 'GET_NOTE_INDEX';

export const SAVE_EDITED_NOTE = 'SAVE_EDITED_NOTE';
export const UPDATE_EDITED_NOTE = 'UPDATE_EDITED_NOTE';
