export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const SELECT_NOTE = 'SELECT_NOTE';
export const UNSELECT_NOTE = 'UNSELECT_NOTE';
export const GET_NOTE_COLOR = 'GET_NOTE_COLOR';
export const CHANGE_NOTE_COLOR = 'CHANGE_NOTE_COLOR';
export const GET_NOTE_INDEX = 'GET_NOTE_INDEX';

export const SAVE_EDITABLE_NOTE = 'SAVE_EDITABLE_NOTE';
export const UPDATE_EDITABLE_NOTE = 'UPDATE_EDITABLE_NOTE';

export const TOGGLE_CHECKBOX_NOTE = ' CHECK_CHECKBOX_NOTE';