export const INIT_NOTES = 'INIT_NOTES';
export const INIT_LABELS = 'INIT_LABELS';

export const ADD_LABEL = 'ADD_LABEL';
export const RENAME_LABEL = 'RENAME_LABEL';

export const GET_EDITABLE_NOTE = 'GET_EDITABLE_NOTE';
export const CLEAR_EDITABLE_NOTE = 'CLEAR_EDITABLE_NOTE';
export const ARCHIVE_NOTE = 'ARCHIVE_NOTE';
export const UNARCHIVE_NOTE = 'UNARCHIVE_NOTE';

export const SHOW_FLASH_MESSAGE = 'SHOW_FLASH_MESSAGE';
export const HIDE_FLASH_MESSAGE = 'HIDE_FLASH_MESSAGE';